### ISSUE TITLE
mongoose_gridfs__WEBPACK_IMPORTED_MODULE_7__ is not a function after upgrade from 0.5.0 to 1.2.48

### ISSUE THREAD

**Issue by MarQs1990** [lykmapipo/mongoose-gridfs#70]
When upgrading from version 0.5.0 to 1.2.48 we get the following errors:
- mongoose_gridfs__WEBPACK_IMPORTED_MODULE_7__ is not a function 
[- DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.

This is our whole dependency tree:
 "dependencies": {
        "@angular/animations": "12.1.4",
        "@angular/cdk": "12.1.4",
        "@angular/common": "12.1.4",
        "@angular/compiler": "12.1.4",
        "@angular/core": "12.1.4",
        "@angular/flex-layout": "12.0.0-beta.34",
        "@angular/forms": "12.1.4",
        "@angular/material": "12.1.4",
        "@angular/material-moment-adapter": "12.0.0",
        "@angular/platform-browser": "12.1.4",
        "@angular/platform-browser-dynamic": "12.1.4",
        "@angular/router": "12.1.4",
        "@datorama/akita": "^2.2.1",
        "@datorama/akita-ngdevtools": "^3.0.2",
        "@fortawesome/fontawesome-pro": "file:.fonts/fontawesome-pro.tar.gz",
        "@material-extended/mde": "^3.0.3",
        "@nest-middlewares/morgan": "^6.0.0",
        "@nestjs/axios": "^0.0.1",
        "@nestjs/common": "^8.0.6",
        "@nestjs/config": "^1.0.1",
        "@nestjs/core": "8.0.6",
        "@nestjs/jwt": "^8.0.0",
        "@nestjs/mongoose": "^8.0.0",
        "@nestjs/passport": "^8.0.1",
        "@nestjs/platform-express": "8.0.6",
        "@nestjs/platform-socket.io": "^8.0.6",
        "@nestjs/websockets": "^8.0.6",
        "@ngneat/hotkeys": "^1.1.1",
        "@ngneat/until-destroy": "^8.0.2",
        "@ngrx/effects": "12.2.0",
        "@ngrx/entity": "12.2.0",
        "@ngrx/store": "12.2.0",
        "@ngrx/store-devtools": "12.2.0",
        "@ngx-pwa/local-storage": "10.0.1",
        "@ngx-translate/core": "13.0.0",
        "@ngx-translate/http-loader": "6.0.0",
        "@sentry/browser": "^6.2.1",
        "@sentry/integrations": "^6.2.1",
        "@sentry/node": "^6.2.1",
        "@sentry/tracing": "^6.2.1",
        "@stomp/stompjs": "^5.4.4",
        "@swimlane/ngx-graph": "^7.2.0",
        "app-root-path": "^3.0.0",
        "chart.js": "^2.9.3",
        "class-transformer": "^0.2.3",
        "class-validator": "^0.11.1",
        "color": "^3.1.2",
        "colors": "^1.4.0",
        "core-js": "^3.8.3",
        "express-fileupload": "^1.1.6",
        "graphql-ld": "^1.1.0",
        "graphql-ld-sparqlendpoint": "^1.0.1",
        "hammerjs": "^2.0.8",
        "helmet": "^3.22.0",
        "jexl": "^2.2.2",
        "jsonld": "^3.1.1",
        "jwt-decode": "^2.2.0",
        "ldapts": "^2.2.1",
        "lodash": "^4.17.19",
        "mongo-gridfs": "^1.1.0",
        "mongodb": "^3.6.5",
        "mongoose": "~5.13.5",
        "mongoose-gridfs": "^0.5.0",
        "morgan": "^1.10.0",
        "multer-gridfs-storage": "^5.0.0",
        "nest-winston": "^1.3.5",
        "ng-mocks": "10.1.2",
        "ng2-charts": "2.4.0",
        "ng4-click-outside": "^1.0.1",
        "ngx-color-picker": "10.0.1",
        "ngx-cookie-service": "10.0.1",
        "ngx-drag-drop": "^2.0.0",
        "ngx-filter-pipe": "^2.1.2",
        "ngx-infinite-scroll": "9.0.0",
        "ngx-json-viewer": "^2.4.0",
        "ngx-let-directive": "^1.0.1",
        "ngx-markdown": "10.1.1",
        "ngx-order-pipe": "2.1.0",
        "ngx-pagination": "5.0.0",
        "ngx-permissions": "8.0.0",
        "ngx-schema-form": "2.4.8",
        "ngx-socket-io": "^3.3.1",
        "ngx-uploader": "10.0.0",
        "node-fetch": "^2.6.1",
        "object-hash": "^2.1.1",
        "passport": "^0.4.1",
        "passport-http-bearer": "^1.0.1",
        "passport-jwt": "^4.0.0",
        "passport-local": "^1.0.0",
        "reflect-metadata": "^0.1.13",
        "rxjs": "7.3.0",
        "sass-loader": "^8.0.2",
        "semver": "^7.3.2",
        "sockjs-client": "^1.5.0",
        "sparqljs": "^3.0.1",
        "svg.draggable.js": "^2.2.2",
        "svg.draw.js": "^2.0.4",
        "svg.js": "^2.7.1",
        "svg.panzoom.js": "^1.2.3",
        "svg.resize.js": "^1.4.3",
        "svg.select.js": "^3.0.1",
        "tslib": "^2.0.0",
        "uuid": "^7.0.3",
        "winston": "^3.3.2",
        "ws": "^7.3.1",
        "z-schema": "^4.2.2",
        "zone.js": "0.11.4"
    }
